apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen-2
  labels:
    app: loadgen-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen-2
  template:
    metadata:
      labels:
        app: loadgen-2
      annotations:
        ebpf-attachment: "rate-limiter"
    spec:
      containers:
      - name: loadgen-2
        image: dushyantbehl/scapy-loadgen:latest
